name: friend_aid_app
description: A Flutter app to help friends in emergency situations.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  geolocator: ^10.0.0
  url_launcher: ^6.1.5
  flutter_local_notifications: ^15.0.0

flutter:
  uses-material-design: true
